### ISSUE TITLE
Problems after upgrading meteor

### ISSUE THREAD

**Issue by thebarty** [peerlibrary/blaze-layout-component#5]
Hi @mitar,

ran into a problem after upgrading from Meteor 1.4 to the latest 1.7:

```
W20180808-11:42:36.974(2)? (STDERR) TypeError: Cannot read property 'setRoot' of undefined
W20180808-11:42:36.974(2)? (STDERR)     at packages/peerlibrary_blaze-layout-component.js:145:13
W20180808-11:42:36.974(2)? (STDERR)     at packages/peerlibrary_blaze-layout-component.js:149:4
W20180808-11:42:36.974(2)? (STDERR)     at packages/peerlibrary_blaze-layout-component.js:157:3
```

A `meteor update --all-packages` gives me this output:
```
This project is already at Meteor 1.7.0.4, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * aldeed:autoform 5.8.1 (6.3.0 is available) 
 * aldeed:collection2 2.10.0 (3.0.0 is available)
 * aldeed:schema-index 1.1.1 (3.0.0 is available)
 * mdg:seo 1.1.0 (3.2.0_1 is available)       
 * meteortoys:allthings 2.3.1 (7.0.1 is available)
 * peerlibrary:blaze-components 0.21.0 (0.22.0 is available)
 * peerlibrary:blaze-layout-component 0.1.2 (0.2.1 is available)
 * peerlibrary:reactive-publish 0.4.0 (0.7.0 is available)
 * percolate:migrations 0.9.8 (1.0.2 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.1.2 is available)
 * aldeed:schema-deny 1.1.0 (3.0.0 is available)
 * coffeescript 1.0.17 (2.2.1_1 is available) 
 * meteortoys:authenticate 2.1.0 (4.0.0 is available)
 * meteortoys:autopub 2.1.0 (4.0.0 is available)
 * meteortoys:blueprint 2.1.0 (4.0.0 is available)
 * meteortoys:email 2.1.0 (4.0.0 is available)
 * meteortoys:hotreload 2.1.0 (4.0.0 is available)
 * meteortoys:listen 2.1.0 (4.0.0 is available)
 * meteortoys:method 3.0.4 (4.0.0 is available)
 * meteortoys:pub 3.0.4 (4.0.0 is available)  
 * meteortoys:result 2.1.0 (4.0.0 is available)
 * meteortoys:shell 2.1.0 (4.0.0 is available)
 * meteortoys:status 2.1.0 (4.0.0 is available)
 * meteortoys:sub 2.1.0 (4.0.0 is available)  
 * meteortoys:throttle 2.1.0 (4.0.0 is available)
 * meteortoys:toykit 2.2.1 (4.0.2 is available)
 * msavin:jetsetter 1.5.2 (4.0.0 is available)
 * msavin:mongol 1.6.2 (7.0.1 is available)   
 * peerlibrary:data-lookup 0.1.0 (0.2.1 is available)
 * peerlibrary:extend-publish 0.3.0 (0.5.0 is available)
 * peerlibrary:fiber-utils 0.6.0 (0.9.1 is available)
 * peerlibrary:reactive-mongo 0.1.1 (0.2.2 is available)
 * peerlibrary:server-autorun 0.5.2 (0.7.1 is available)
 * softwarerero:accounts-t9n 1.3.11 (2.3.1 is available)
```

Do you think you can upgrade the peerlibrary ecosystem to be compatible?

**Comment by mitar** [comment]
Try using `peerlibrary:blaze-layout-component@0.3.0`.
